"""Artifact synthesis for the simulated backend.

Generates documents that satisfy a spec's declared contract -- the headings it
must have, the topics it must cover, the JSON keys it must carry -- by reading
the contract itself. This is deliberately mechanical. It proves the pipeline
moves real files through real boundaries; it does not pretend to be analysis,
and every document it writes says so at the top.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from .agents.base import AgentSpec, FileContains, HasHeadings, MinWords, ValidJson

BANNER = (
    "> **Generated by the simulated backend.** Structure is real and contract-"
    "checked; the content is scaffolding, not researched analysis. Re-run with "
    "`ANTHROPIC_API_KEY` set to have a model author this.\n"
)


def _contract(spec: AgentSpec, rel: str) -> tuple[list[str], int, int, list[str]]:
    """Read this artifact's obligations out of the spec's postconditions."""
    needles: list[str] = []
    headings, words = 0, 0
    json_keys: list[str] = []
    for chk in spec.postconditions:
        path = getattr(chk, "path", None)
        if path != rel:
            continue
        if isinstance(chk, FileContains):
            needles.extend(chk.needles)
        elif isinstance(chk, HasHeadings):
            headings = max(headings, chk.minimum)
        elif isinstance(chk, MinWords):
            words = max(words, chk.minimum)
        elif isinstance(chk, ValidJson):
            json_keys.extend(chk.keys)
    return needles, headings, words, json_keys


def _brief(root: Path) -> str:
    for cand in ("AGENT/problem_statement.md", "PROBLEM.md", "README.md"):
        p = root / cand
        if p.is_file():
            return p.read_text(encoding="utf-8", errors="replace")[:1500]
    return "(no problem statement found)"


def synthesize(
    spec: AgentSpec, rel: str, root: Path, inputs: dict[str, str], prior: str
) -> str:
    needles, min_headings, min_words, json_keys = _contract(spec, rel)

    if rel.endswith(".json"):
        return _synthesize_json(spec, rel, root, json_keys)
    if rel.endswith(".py"):
        return _synthesize_python(spec, rel)
    if rel.endswith(".html"):
        return _synthesize_html(spec, rel)
    if rel.endswith(".sql"):
        return _synthesize_sql(spec, rel)
    if rel.endswith("slides.md"):
        return _synthesize_slides(spec, root)
    if Path(rel).name == ".env.example":
        return (
            "# Copy to .env and fill in. Never commit the filled-in file.\n"
            "ANTHROPIC_API_KEY=sk-ant-your-key-here\n"
            "APP_ENV=development\n"
            "PORT=8000\n"
        )

    title = Path(rel).stem.replace("_", " ").title()
    lines: list[str] = [f"# {title}", "", BANNER, ""]
    lines += [
        f"**Owner:** {spec.title} (`{spec.name}`, {spec.team} team)  ",
        f"**Produced:** {date.today().isoformat()}  ",
        f"**Contract:** {rel}",
        "",
        "## Purpose",
        "",
        spec.mission.strip().split("\n\n")[0],
        "",
    ]

    # One section per contracted topic -- this is what the postcondition checks.
    for n in needles:
        lines += [
            f"## {n.title()}",
            "",
            f"This section is required by the artifact contract for `{rel}`; the "
            f"{spec.title} must address **{n}** before this task can pass validation. "
            f"In a model-backed run this is where the analysis of {n} lives, grounded "
            f"in the inputs listed below rather than in assumption.",
            "",
        ]

    # Pad to the contracted heading count with real structural sections.
    extra = ["Method", "Evidence", "Open Questions", "Handoff Notes", "Risks"]
    i = 0
    while len(needles) + 4 + i < min_headings and i < len(extra):
        lines += [f"## {extra[i]}", "", f"Placeholder for {extra[i].lower()}.", ""]
        i += 1

    lines += ["## Inputs consulted", ""]
    if inputs:
        for k, v in inputs.items():
            first = next((l for l in v.splitlines()[1:] if l.strip()), "(empty)")
            lines.append(f"- `{k}` — read; opens with: {first.strip()[:100]}")
    else:
        lines.append("- none (this specialist has no declared inputs)")
    lines += ["", "## Prior art consulted", ""]
    lines.append(
        ("```\n" + prior.strip()[:900] + "\n```") if prior.strip()
        else "- knowledge_search not available to this specialist."
    )
    lines += [
        "",
        "## Limitations",
        "",
        "- Produced without a model; treat every statement above as a placeholder.",
        "- No external sources were consulted, so nothing here is citable.",
        "- The structure, file location and validation status ARE meaningful:",
        "  this document passed its declared postconditions.",
        "",
    ]

    body = "\n".join(lines)
    # Meet the word floor with an explicit filler note rather than padded prose.
    if min_words:
        deficit = min_words - len(body.split())
        if deficit > 0:
            body += (
                "\n## Contract padding\n\n"
                f"This artifact declares a {min_words}-word floor to stop specialists "
                "from passing a stub off as finished work. The simulated backend has "
                "no analysis to put here, so it says so explicitly rather than "
                "generating filler that reads like content. "
                + ("Placeholder. " * max(0, deficit // 1 + 5))
            )
    return body


def _synthesize_json(spec: AgentSpec, rel: str, root: Path, keys: list[str]) -> str:
    base: dict = {
        "_generated_by": "SimulatedBackend",
        "_warning": "Scaffolding, not model-authored content.",
        "owner": spec.name,
        "produced": date.today().isoformat(),
    }
    defaults = {
        "required_files": ["README.md"],
        "checklist": [],
        "deliverables": [],
        "format": "zip",
        "deadline": "unknown",
        "verified": False,
        "items": [],
        "tasks": [],
        "criteria": [],
    }
    for k in keys:
        base[k] = defaults.get(k, f"<{k}: not determined in simulated run>")
    return json.dumps(base, indent=2)


# ---------------------------------------------------------------------------
# Code artifacts. These must be syntactically valid -- the engineering specs
# assert it with a `python_parses` postcondition, and a scaffolding generator
# that cannot satisfy the contract it is testing is not testing anything.
# ---------------------------------------------------------------------------

def _synthesize_python(spec: AgentSpec, rel: str) -> str:
    module = Path(rel).stem
    return f'''"""{module} -- placeholder produced by the simulated backend.

Owner: {spec.title} ({spec.name})
Generated: {date.today().isoformat()}

NOT AN IMPLEMENTATION. This file exists so the pipeline can verify that the
{spec.name} write scope, artifact contract and syntax postcondition all hold.
Re-run with ANTHROPIC_API_KEY set to have a model write the real thing.
"""

from __future__ import annotations

PLACEHOLDER = True
OWNER = "{spec.name}"


def not_implemented() -> str:
    """Return an honest marker rather than pretending to work."""
    return f"{{OWNER}}: no implementation; simulated run"


if __name__ == "__main__":
    print(not_implemented())
'''


def _synthesize_html(spec: AgentSpec, rel: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Placeholder — {spec.title}</title>
  <style>
    :root {{ --ink:#111; --bg:#fafafa; --accent:#c33; }}
    body {{ margin:0; font:16px/1.5 system-ui,sans-serif; color:var(--ink);
           background:var(--bg); display:grid; place-items:center; min-height:100vh; }}
    main {{ max-width:34rem; padding:2rem; }}
    h1 {{ font-size:1.5rem; margin:0 0 .5rem; }}
    .warn {{ color:var(--accent); font-weight:600; }}
  </style>
</head>
<body>
  <main>
    <h1>Placeholder interface</h1>
    <p class="warn">Generated by the simulated backend — this is not the real UI.</p>
    <p>Owner: {spec.title} (<code>{spec.name}</code>). This file exists to prove the
       artifact contract and write scope hold. Re-run with an API key set to have a
       model build against <code>DESIGN/ux.md</code> and <code>DESIGN/ui.md</code>.</p>
  </main>
</body>
</html>
"""


def _synthesize_sql(spec: AgentSpec, rel: str) -> str:
    return f"""-- {rel} -- placeholder produced by the simulated backend.
-- Owner: {spec.title} ({spec.name}), {date.today().isoformat()}
-- NOT A REAL SCHEMA. Exists to satisfy the artifact contract during testing.

CREATE TABLE placeholder (
    id          INTEGER PRIMARY KEY,
    note        TEXT NOT NULL DEFAULT 'simulated run; no real schema designed',
    created_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_placeholder_created ON placeholder (created_at);
"""


def _synthesize_slides(spec: AgentSpec, root: Path) -> str:
    """A deck in the format build_pptx parses: `## Title`, `- bullet`, `Notes:`.

    The generic markdown path cannot produce this -- the slide-count check is a
    Custom postcondition, which `_contract` cannot introspect the way it reads
    FileContains or HasHeadings. Formats with their own grammar get their own
    generator rather than a heading count that happens to line up.
    """
    name = "The Product"
    brand = root / "DESIGN/brand.md"
    if brand.is_file():
        for line in brand.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.lower().startswith("## product name"):
                name = "The Product"
                break

    slides = [
        ("The Problem", [
            "Who is hurting, and how often",
            "What it costs them today",
            "Why existing options do not fix it",
        ], "Open on the user, not the technology. One concrete person."),
        ("The Insight", [
            "The non-obvious thing we noticed",
            "Why it changes what is buildable",
        ], "This is the sentence a judge should remember."),
        (f"{name}: The Solution", [
            "What it does, in one line",
            "The core interaction",
            "What makes it different",
        ], "Keep to one idea. Detail belongs in the demo."),
        ("How It Works", [
            "Architecture in three boxes",
            "The part that is genuinely hard",
            "What we built versus what we integrated",
        ], "Judges probe here. Be precise about what is ours."),
        ("Results", [
            "TODO: real measured figure — none available in a simulated run",
            "TODO: baseline to compare against",
            "TODO: what the number does NOT show",
        ], "Never put an unmeasured number on this slide. Baseline or it means nothing."),
        ("Impact", [
            "Who benefits and by how much",
            "What changes if this ships",
        ], "Tie back to the judging rubric's impact criterion."),
        ("What's Next", [
            "The honest current limitation",
            "The next thing we would build",
        ], "Naming a real limitation buys credibility for everything else."),
    ]

    out = [
        "# Slide deck",
        "",
        BANNER,
        f"Owner: {spec.title} ({spec.name}). Placeholders are marked TODO on purpose:",
        "the simulated backend has no measured results and will not invent any.",
        "",
    ]
    for title, bullets, notes in slides:
        out.append(f"## {title}")
        out.append("")
        out.extend(f"- {b}" for b in bullets)
        out.append(f"Notes: {notes}")
        out.append("")
    return "\n".join(out)
